Phase f04
Star-Academy/Summer1400-FE-Team8 pull request #3
Opened 2021-08-04 18:47 UTC by bolnik

2021-08-04 19:34 UTC, BijanEisapour requested changes

2021-08-04 19:34 UTC, BijanEisapour commented on player.html
> +              <button id="PlayPause" title="توقف یا اجرا"><img src="assets/images/player/music/play_arrow.svg"
<p dir='rtl' align='right'>
کلاس‌ها و آیدی‌ها باید kebab-case باشن

2021-08-04 19:34 UTC, BijanEisapour commented on scripts/login-validation.js
> +    if(email===''|| password===''){
<p dir='rtl' align='right'>
از prettier استفاده کنید که این spaceها رو درست بندازه

2021-08-04 19:34 UTC, BijanEisapour commented on scripts/music-search.js
> +
<p dir='rtl' align='right'>
enter اضافی پاک شه

2021-08-04 19:34 UTC, BijanEisapour commented on scripts/music-search.js
> +const all = document.querySelector('.search-container form #all');
<p dir='rtl' align='right'>
مگه آیدی رو به بیش از یک المان نسبت دادید که اینجوری select میکنید؟ خود آیدی به خودیِ خود کافیه

2021-08-04 19:34 UTC, BijanEisapour commented on style/scss/components/_side-menu.scss
> +  // display: none;
.

2021-08-04 19:34 UTC, BijanEisapour commented on style/scss/components/_side-menu.scss
>          vertical-align: -8.1px;
<p dir='rtl' align='right'>
این دیگه چیه؟

2021-08-04 19:34 UTC, BijanEisapour commented on style/scss/layouts/_login.scss
> +  form  > div >   #mail_error , #pass_error
<p dir='rtl' align='right'>
آیدی خالی کافیه

2021-08-04 19:34 UTC, BijanEisapour commented on style/scss/layouts/_signup.scss
> +      color: #fff;
<p dir='rtl' align='right'>
از hsl استفاده کنید که با یه نگاه بشه فهمید چه رنگیه

2021-08-04 20:54 UTC, BijanEisapour approved these changes

2021-08-06 08:11 UTC, heidarzade-mh approved these changes

2021-08-06 08:12 UTC, merged